name: Uppdatera dokumentlista

on:
  push:
    paths:
      - 'docs/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lista alla filer i docs
        run: |
          # Vi använder null-separerade filnamn
          find docs -maxdepth 1 -type f -print0 > files.txt

      - name: Generera docs-array
        run: |
          ARRAY="["
          while IFS= read -r -d '' f; do
            FILE_NAME="$(basename "$f")"
            NAME="${FILE_NAME%.*}"   # Ta bort filändelsen
            DESC="Kort beskrivning av $NAME"
            # Escape quotes och backslashes för JSON
            NAME_ESCAPED=$(echo "$NAME" | sed 's/\\/\\\\/g; s/"/\\"/g')
            DESC_ESCAPED=$(echo "$DESC" | sed 's/\\/\\\\/g; s/"/\\"/g')
            FILE_ESCAPED=$(echo "$f" | sed 's/\\/\\\\/g; s/"/\\"/g')
            ARRAY+="{\"name\":\"$NAME_ESCAPED\",\"desc\":\"$DESC_ESCAPED\",\"file\":\"$FILE_ESCAPED\"},"
          done < files.txt
          ARRAY="${ARRAY%,}]"
          echo "ARRAY=$ARRAY" >> $GITHUB_ENV

      - name: Uppdatera dokument.html
        run: |
          sed -i '/const docs = \[/,/];/c\const docs = '"$ARRAY"';' dokument.html

      - name: Commit & push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dokument.html
          git commit -m "Uppdaterad docs-array automatiskt via GitHub Action" || echo "Inga ändringar att commita"
          git push
