name: Uppdatera dokumentlista

on:
  push:
    paths:
      - 'docs/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lista filer i docs och sortera alfabetiskt
        run: |
          echo "Filer i docs/ som hittas:"
          find docs -maxdepth 1 -type f -print0 | sort -z | while IFS= read -r -d '' f; do
            echo "$f"
          done > files.txt

      - name: Generera docs-array med URL-encoding och filtyp
        run: |
          ARRAY="["
          while IFS= read -r -d '' f; do
            FILE_NAME="$(basename "$f")"
            NAME="${FILE_NAME%.*}"
            DESC="Kort beskrivning av $NAME"
            EXT="${FILE_NAME##*.}"
            ICON="$([ "$EXT" = "pdf" ] && echo "pdf" || ([ "$EXT" = "docx" ] || [ "$EXT" = "doc" ] && echo "word" || echo "file"))"
            # URL-encode filväg
            FILE_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$f'''))")
            # Escape quotes/backslashes för JSON
            NAME_ESCAPED=$(echo "$NAME" | sed 's/\\/\\\\/g; s/"/\\"/g')
            DESC_ESCAPED=$(echo "$DESC" | sed 's/\\/\\\\/g; s/"/\\"/g')
            ARRAY+="{\"name\":\"$NAME_ESCAPED\",\"desc\":\"$DESC_ESCAPED\",\"file\":\"$FILE_ENCODED\",\"icon\":\"$ICON\"},"
          done < files.txt
          ARRAY="${ARRAY%,}]"
          echo "ARRAY=$ARRAY" >> $GITHUB_ENV
          echo "Docs-arrayen genererad:"
          echo "$ARRAY"

      - name: Uppdatera dokument.html
        run: |
          sed -i '/const docs = \[/,/];/c\const docs = '"$ARRAY"';' dokument.html
          echo "dokument.html uppdaterad med nya filer."

      - name: Commit & push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dokument.html
          git commit -m "Uppdaterad docs-array automatiskt med ikoner och sortering" || echo "Inga ändringar att commita"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/HissenInstruktionsfilmer/instruktionsfilmer.git HEAD:main
