name: Uppdatera dokumentlista

on:
  push:
    paths:
      - 'docs/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lista filer i docs och sortera alfabetiskt
        run: |
          find docs -maxdepth 1 -type f -print0 | sort -z > files.txt

      - name: Generera docs-array med URL-encoding och filtyp
        run: |
          ARRAY="["
          while IFS= read -r -d '' f; do
            FILE_NAME="$(basename "$f")"
            NAME="${FILE_NAME%.*}"
            DESC="Kort beskrivning av $NAME"
            EXT="${FILE_NAME##*.}"
            ICON="$([ "$EXT" = "pdf" ] && echo "pdf" || ([ "$EXT" = "docx" ] || [ "$EXT" = "doc" ] && echo "word" || echo "file"))"
            FILE_ENCODED=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$f'''))")
            NAME_ESCAPED=$(echo "$NAME" | sed 's/\\/\\\\/g; s/"/\\"/g')
            DESC_ESCAPED=$(echo "$DESC" | sed 's/\\/\\\\/g; s/"/\\"/g')
            ARRAY+="{\"name\":\"$NAME_ESCAPED\",\"desc\":\"$DESC_ESCAPED\",\"file\":\"$FILE_ENCODED\",\"icon\":\"$ICON\"},"
          done < files.txt
          ARRAY="${ARRAY%,}]"
          echo "ARRAY=$ARRAY" >> $GITHUB_ENV

      - name: Uppdatera dokument.html
        run: |
          # Ersätt alltid docs-arrayen oavsett innehåll
          sed -z -i 's|const docs = \[[^]]*\];|const docs = '"$ARRAY"';|' dokument.html
          echo "dokument.html uppdaterad med nya filer:"
          grep "const docs" dokument.html

      - name: Skapa Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Uppdaterad docs-array automatiskt med ikoner och sortering"
          branch: update-docs
          base: main
          title: "Uppdatera docs"
          body: "Denna PR uppdaterar docs-array automatiskt med ikoner och sortering."
          allow-empty: true
